language: node_js

node_js:
  - "12.13.0"

# safelist
branches:
  only:
  - master

notifications:
  email:
    recipients:
      - markeyme@163.com
  on_success: change
  on_failure: always

install:
  - npm i

after_success: npm run coverage
